apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: myproject-deploy
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: ""
  source:
    path: 'yamls/'
    repoURL: 'https://github.com/prathmesh-rajmane/argo-cd.git'
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
